/Users/gregmoyle/picobrew_pico/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
cat: /etc/os-release: No such file or directory
[2025-08-20 00:48:46,065] ERROR in tilt: changelist must be an iterable of select.kevent objects
[2025-08-20 00:48:46,065] ERROR in tilt: Error accessing bluetooth device. Shutting down Tilt thread...
Exception ignored in: <function BaseEventLoop.__del__ at 0x105dbb550>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 60, in close
    for sig in list(self._signal_handlers):
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'
/Users/gregmoyle/picobrew_pico/app/main/tilt.py:100: RuntimeWarning: coroutine 'start_infinite_scan' was never awaited
  return
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
[2025-08-20 00:53:01,251] WARNING in routes_server: current device doesn't support 'ifconfig' error=1 output=b'192.168.172.188\n'
/bin/sh: pinout: command not found
Already up to date.
Requirement already satisfied: aenum==3.1.15 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.1.15)
Requirement already satisfied: bleak==0.20.2 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.20.2)
Requirement already satisfied: dnspython==2.3.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2.3.0)
Requirement already satisfied: eventlet==0.36.1 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.36.1)
Requirement already satisfied: Flask_Cors==4.0.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: Flask_SocketIO==5.3.6 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (5.3.6)
Requirement already satisfied: Flask==2.2.5 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.2.5)
Requirement already satisfied: MarkupSafe==2.1.5 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (2.1.5)
Requirement already satisfied: mock==5.1.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (5.1.0)
Requirement already satisfied: packaging==21.3 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (21.3)
Requirement already satisfied: python-dateutil==2.9.0.post0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (2.9.0.post0)
Requirement already satisfied: requests==2.31.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (2.31.0)
Requirement already satisfied: ruamel.yaml==0.18.6 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (0.18.6)
Requirement already satisfied: webargs==8.3.0 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (8.3.0)
Requirement already satisfied: Werkzeug==2.2.3 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (2.2.3)
Requirement already satisfied: beautifulsoup4==4.12.3 in ./.venv/lib/python3.9/site-packages (from -r requirements.txt (line 16)) (4.12.3)
Requirement already satisfied: async-timeout<5,>=3.0.0 in ./.venv/lib/python3.9/site-packages (from bleak==0.20.2->-r requirements.txt (line 2)) (4.0.3)
Requirement already satisfied: pyobjc-core<10.0.0,>=9.0.1 in ./.venv/lib/python3.9/site-packages (from bleak==0.20.2->-r requirements.txt (line 2)) (9.2)
Requirement already satisfied: pyobjc-framework-CoreBluetooth<10.0.0,>=9.0.1 in ./.venv/lib/python3.9/site-packages (from bleak==0.20.2->-r requirements.txt (line 2)) (9.2)
Requirement already satisfied: pyobjc-framework-libdispatch<10.0.0,>=9.0.1 in ./.venv/lib/python3.9/site-packages (from bleak==0.20.2->-r requirements.txt (line 2)) (9.2)
Requirement already satisfied: greenlet>=1.0 in ./.venv/lib/python3.9/site-packages (from eventlet==0.36.1->-r requirements.txt (line 4)) (3.2.4)
Requirement already satisfied: python-socketio>=5.0.2 in ./.venv/lib/python3.9/site-packages (from Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (5.13.0)
Requirement already satisfied: Jinja2>=3.0 in ./.venv/lib/python3.9/site-packages (from Flask==2.2.5->-r requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: itsdangerous>=2.0 in ./.venv/lib/python3.9/site-packages (from Flask==2.2.5->-r requirements.txt (line 7)) (2.2.0)
Requirement already satisfied: click>=8.0 in ./.venv/lib/python3.9/site-packages (from Flask==2.2.5->-r requirements.txt (line 7)) (8.1.8)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./.venv/lib/python3.9/site-packages (from Flask==2.2.5->-r requirements.txt (line 7)) (8.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.venv/lib/python3.9/site-packages (from packaging==21.3->-r requirements.txt (line 10)) (3.2.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil==2.9.0.post0->-r requirements.txt (line 11)) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 12)) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 12)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 12)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 12)) (2025.8.3)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in ./.venv/lib/python3.9/site-packages (from ruamel.yaml==0.18.6->-r requirements.txt (line 13)) (0.2.12)
Requirement already satisfied: marshmallow>=3.0.0 in ./.venv/lib/python3.9/site-packages (from webargs==8.3.0->-r requirements.txt (line 14)) (4.0.0)
Requirement already satisfied: soupsieve>1.2 in ./.venv/lib/python3.9/site-packages (from beautifulsoup4==4.12.3->-r requirements.txt (line 16)) (2.7)
Requirement already satisfied: pyobjc-framework-Cocoa>=9.2 in ./.venv/lib/python3.9/site-packages (from pyobjc-framework-CoreBluetooth<10.0.0,>=9.0.1->bleak==0.20.2->-r requirements.txt (line 2)) (9.2)
Requirement already satisfied: zipp>=3.20 in ./.venv/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->Flask==2.2.5->-r requirements.txt (line 7)) (3.23.0)
Requirement already satisfied: backports-datetime-fromisoformat in ./.venv/lib/python3.9/site-packages (from marshmallow>=3.0.0->webargs==8.3.0->-r requirements.txt (line 14)) (2.0.3)
Requirement already satisfied: typing-extensions in ./.venv/lib/python3.9/site-packages (from marshmallow>=3.0.0->webargs==8.3.0->-r requirements.txt (line 14)) (4.14.1)
Requirement already satisfied: bidict>=0.21.0 in ./.venv/lib/python3.9/site-packages (from python-socketio>=5.0.2->Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (0.23.1)
Requirement already satisfied: python-engineio>=4.11.0 in ./.venv/lib/python3.9/site-packages (from python-socketio>=5.0.2->Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (4.12.2)
Requirement already satisfied: simple-websocket>=0.10.0 in ./.venv/lib/python3.9/site-packages (from python-engineio>=4.11.0->python-socketio>=5.0.2->Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: wsproto in ./.venv/lib/python3.9/site-packages (from simple-websocket>=0.10.0->python-engineio>=4.11.0->python-socketio>=5.0.2->Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: h11<1,>=0.9.0 in ./.venv/lib/python3.9/site-packages (from wsproto->simple-websocket>=0.10.0->python-engineio>=4.11.0->python-socketio>=5.0.2->Flask_SocketIO==5.3.6->-r requirements.txt (line 6)) (0.16.0)
/Users/gregmoyle/picobrew_pico/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
cat: /etc/os-release: No such file or directory
[2025-08-20 00:53:21,650] ERROR in tilt: changelist must be an iterable of select.kevent objects
[2025-08-20 00:53:21,650] ERROR in tilt: Error accessing bluetooth device. Shutting down Tilt thread...
Exception ignored in: <function BaseEventLoop.__del__ at 0x104497550>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 60, in close
    for sig in list(self._signal_handlers):
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'
/Users/gregmoyle/picobrew_pico/app/main/tilt.py:100: RuntimeWarning: coroutine 'start_infinite_scan' was never awaited
  return
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
[2025-08-20 00:53:23,474] WARNING in routes_server: current device doesn't support 'ifconfig' error=1 output=b'192.168.172.188\n'
/bin/sh: pinout: command not found
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
[2025-08-20 00:53:26,639] WARNING in routes_server: current device doesn't support 'ifconfig' error=1 output=b'192.168.172.188\n'
/bin/sh: pinout: command not found
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
[2025-08-20 00:54:10,521] WARNING in routes_server: current device doesn't support 'ifconfig' error=1 output=b'192.168.172.188\n'
/bin/sh: pinout: command not found
